CXX = g++
CXXFLAGS = -Wall -Wextra -Iinclude -O3 -std=c++23 -mconsole

TARGET = disassemble
BUILD_DIR = build

HDRS := $(wildcard include/*.h)
SRCS := $(wildcard src/*.cpp) $(wildcard src/**/*.cpp)
OBJS := $(SRCS:src/%.cpp=$(BUILD_DIR)/%.o)

all: $(BUILD_DIR)/$(TARGET)

$(BUILD_DIR)/$(TARGET): $(OBJS)
	@mkdir -p $(BUILD_DIR)
	$(CXX) $(OBJS) -o $@ $(CXXFLAGS)

$(BUILD_DIR)/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: clean
clean:
	@rm -rf $(BUILD_DIR)